#g++ -o prep_temp_input_phase1.exe prep_temp_input_phase1.C `root-config --cflags --libs`

arun3: prep_temp_input_phase1.C
	g++ -o prep_temp_input_phase1 prep_temp_input_phase1.C \
	`root-config --cflags --libs`
	@echo 'done: prep_temp_input_phase1'